<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>AgentCli</AssemblyName>
    <RootNamespace>AgentCli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MigrationStudio.Core\MigrationStudio.Core.csproj" />
  </ItemGroup>

</Project>
